
development:
  adapter: postgresql
  encoding: unicode
  database: bellazita_development
  pool: 5
  host: localhost
  #username: shoplist
  #password:

test:
  adapter: postgresql
  encoding: unicode
  database: bellazita_test
  pool: 5
  host: localhost
  #username: shoplist
  #password:

